# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/healthai_prod
spring.datasource.username=health_admin
spring.datasource.password=secure_password_123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Security
app.security.jwt.secret=${HEALTH_KEY_TEMPO:maSuperCleSecreteTresLongueEtSansCaracteresSpeciauxPourEviterLesErreursDeDecodage123456}